### ISSUE TITLE
buggy : query and announce

### ISSUE THREAD

**Issue by mmmmm-sbi** [flightcrank/JRatioBoost#12]
transmission294 client and also custom client *(transmission and qbittorrent and utorrent) buggy : query and announce .

**Comment by mmmmm-sbi** [comment]
i don't have ktorrent to test it .

**Comment by flightcrank** [comment]
whats buggy about the query and announce. ?

As a side note i added the ability to send your own user agent string to any torrent's tracker. So it can match exactly to any supported client. not that the user agent even matters in most trackers but i did add it in 😁

**Comment by mmmmm-sbi** [comment]
### JRatioBoost2
```
GET /announce?info_hash=%20%94%15t~%d5%16%f9%c2%fd%8cx%a2K%fe-%f6~CU&peer_id=-TR406p%bf%0a4%b2%29%daq%043%e2%5cQc&port=6881&uploaded=0&downloaded=0&left=0&compact=1&event=started HTTP/1.1
User-Agent: Transmission/4.0.6.p
Host: removed
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
```

### Transmission start
```
GET /announce?info_hash=%20%94%15t~%D5%16%F9%C2%FD%8Cx%A2K%FE-%F6~CU&peer_id=-TR4060-7hvlgrs6zrar&port=45678&uploaded=0&downloaded=0&left=844289209932&numwant=80&key=934CB06E&compact=1&supportcrypto=1&event=started HTTP/1.1
Host: removed
User-Agent: Transmission/4.0.6
Accept: */*
Accept-Encoding: deflate, gzip
```

### Transmission stop
```
GET /announce?info_hash=%20%94%15t~%D5%16%F9%C2%FD%8Cx%A2K%FE-%F6~CU&peer_id=-TR4060-7hvlgrs6zrar&port=45678&uploaded=0&downloaded=0&left=844289209932&numwant=0&key=934CB06E&compact=1&supportcrypto=1&event=stopped HTTP/1.1
Host: removed
User-Agent: Transmission/4.0.6
Accept: */*
Accept-Encoding: deflate, gzip
```

**Comment by flightcrank** [comment]
Theres nothing buggy about it. Its a valid query string. Its clearly not the same and has missing key value pairs. However torrent clients are free to change their query strings at any time for any reason, as long as they are valid, theres no real problem. You will find that different versions of the same client either older or newer will have changed their query stings over time for a variety of reasons. As long as they are valid there shouldn't be any problem.

If you receive a error message back from the tracker relating to the query that is sent then thats a problem worth investigation. Mimicking any clients exact query-string is a mugs game, as they are subject to change at any time for any reason.

Theres nothing buggy about it. Its just not identical, because it doesn't need to be. If you get an error back from the tracker let me know and ill investigate. But if it ain't broke, don't fix it.

**Comment by mmmmm-sbi** [comment]
if you don't make JRatioBoost query and announce identical as real client then its detectable .

**Comment by flightcrank** [comment]
> if you don't make JRatioBoost query and announce identical as real client then its detectable .

As i stated in my post above, the real clients change their own query stings all the time. They are all subject to change at any moment. They do not get detected as fake clients for that very reason.  Neither will any torrent spoofing program.

if your that paranoid you can change the following lines of the TrackerConnect.java file to what ever query sting you like. 

* [line 39](https://github.com/flightcrank/JRatioBoost/blob/81032d93c4bdd837c1e9e5ea8fc330bd417c930e/src/TrackerConnect.java#L39)
* [line 52](https://github.com/flightcrank/JRatioBoost/blob/81032d93c4bdd837c1e9e5ea8fc330bd417c930e/src/TrackerConnect.java#L52)

but you will just be changing it again when ever your clients makes a change to theirs. Which they do all the time, and no one ever gets banned because its normal behavior. Which is why tracker admins dont go through every torrent client and sniff out their query stings.... because they change all the time.

Its a non issue.

**Comment by mmmmm-sbi** [comment]
no client changes that each version release , also there aren't  two differ query and announce
for the same version release , also the peer_id incorrect , its not normal .

**Comment by flightcrank** [comment]
> no client changes that each version release , also there aren't two differ query and announce for the same version release ,


yes there is, if you think transmission or any other client kept the same query string from their first release and never changed it your mistaken. 

> also the peer_id incorrect , its not normal .

according to the [BitTorrentSpecification](https://wiki.theory.org/BitTorrentSpecification#peer_id) the peer id is normal. most clients use the "Azureus-style"

>Azureus-style uses the following encoding: '-', two characters for client id, four ascii digits for version number, '-', followed by random numbers. 

thats what JRatioBoost uses. so its a valid peerID thats why it gets accepted by every tracker ive ever used it on. If you want to make it identical to the peerID of transmission then by all means copy and paste it in the the 2 lines i specified above
