### ISSUE TITLE
bug: when hit stop torrent there is nothing sent to tracker.

### ISSUE THREAD

**Issue by mmmmm-sbi** [flightcrank/JRatioBoost#13]
bug: when hit stop torrent there is nothing sent to tracker.

**Comment by flightcrank** [comment]
This is intentional. It was included many years ago but removed. Provisions exist in the program to inform the user how much upload data the tracker has received. The update interval can be changed while the torrent is running to a few seconds. It has no bearing on spoofing as this is a behavior present in actual torrent clients like Transmission up to version 4 https://github.com/transmission/transmission/issues/196.

If it was needed i would put it in, but it effects nothing and allows the program to close faster without having to make another connection to send the stopped event and wait for a response.

**Comment by mmmmm-sbi** [comment]
### Transmission stop
```
GET /announce?info_hash=%20%94%15t~%D5%16%F9%C2%FD%8Cx%A2K%FE-%F6~CU&peer_id=-TR4060-7hvlgrs6zrar&port=45678&uploaded=0&downloaded=0&left=844289209932&numwant=0&key=934CB06E&compact=1&supportcrypto=1&event=stopped HTTP/1.1
Host: removed
User-Agent: Transmission/4.0.6
Accept: */*
Accept-Encoding: deflate, gzip
```

**Comment by flightcrank** [comment]
As i stated in my post above, the stopped event is simply not needed. You can never get banned for not sending the stopped event because torrent clients close or crash all the time with out without ever sending one. Its not something tracker admins look for to determine if some one is spoofing or not because legitimate clients don't send stop events all the time for the reasons i already outlined.

Its simply not needed, if that ever changes ill add it in.

**Comment by mmmmm-sbi** [comment]
but its waist of some uploads not sent to tracker .

**Comment by mmmmm-sbi** [comment]
you say manual and i say auto .

**Comment by flightcrank** [comment]
> you say manual and i say auto .

not quite sure what you mean there

**Comment by flightcrank** [comment]
> also event=stop not sent at query (its not normal my client crash each time)

This point has already been addressed. Clients are dont need to crash at all. Simply closing the torrent client like in transmission never sent the stopped event. So it has been normal behavior in torrent clients for years. If you want to implement it ill accept at push request.
