### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by Liu-Kai-1991** [flightcrank/JRatioBoost#2]
on torrentleech

**Comment by flightcrank** [comment]
interesting, I've tested and used it without problem on torrent leech. Let me look into it and see if i can track down the issue.

**Comment by flightcrank** [comment]
well i can confirm torrentleech working fine on my end. It looks like and error you your end either with your ISP or VPN/firewall/proxy/router etc.

I suggest you try again and disable software that could cause problems and try it from a default connection point standpoint. I had a user that had an issue caused by his vpn. 

Ill leave the issue open for a short time so you can try again and respond to see if thats the problem.
